version: '3'

networks:
  devops:

services:
  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - devops

  grafana:
    image: grafana/grafana:8.3.1
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    networks:
      - devops

  ms-metrics-publisher:
    image: ms-metrics-publisher:latest
    ports:
      - '8080:8080'
    networks:
      - devops
